apiVersion: apps/v1
kind: Deployment
metadata:
  name: dningy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dningy
  template:
    metadata:
      labels:
        app: dningy
    spec:
      containers:
      - image: okteto.dev/dningy:latest
        name: dningy
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "71fb5524-a63d-48d1-bc45-f768e9b17eed"
        - name: Vless_Path
          value: "/budheigldsg"
        - name: Vmess_UUID
          value: "c61cdca4-261b-40f2-b417-00979b84e833"
        - name: Vmess_Path
          value: "/ndokfgoisof"
        - name: Share_Path
          value: "/udjogjoafgj"
